#!/usr/bin/php
<?php

use svn2ftp\Cli;
use svn2ftp\SubversionRepository;
use svn2ftp\FTPClient;

$version = "v1.0.0";

require('lib/svn2ftp/Cli.php');
require('lib/svn2ftp/SubversionRepository.php');
require('lib/svn2ftp/FTPClient.php');

$base_path = dirname(__FILE__);

$cli = new Cli($base_path);

$config = $cli->getConfig();

$cli->output("cli.subversion.extracting", $config->get('path.base.local'));

$svn = new SubversionRepository($config->get('path.base.local'), $config->get('path.base.svn'));
$job = $svn->extract($cli->getRevision());

$ftp = new FTPClient();

$cli->output("cli.ftp.connecting", $config->get('ftp.host'));
$ftp->open($config->get('ftp.host'));
$cli->output("cli.ok");

$cli->output("cli.ftp.authenticating", $config->get('ftp.username'));
$ftp->login($config->get('ftp.username'), $config->get('ftp.password'));
$cli->output("cli.ok");

$base_ftp = $config->get('path.base.ftp');
$base_local = $config->get('path.base.local');

foreach($job->getFilesToUpload() as $file) {
    $cli->output("cli.ftp.uploading", $file);
    $ftp->put($file, $base_local, $base_ftp);
    $cli->output("cli.ok");
}

foreach($job->getFilesToDelete() as $file) {
    $cli->output("cli.ftp.deleting", $file);
    $ftp->delete($file, $base_ftp);
    $cli->output("cli.ok");
}

$ftp->close();